version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      DIFFICULTY: "hard"
      MOTD: "Welcome to GabirU Felpudo Server"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      MEMORY: "2G"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data
volumes:
  minecraft-data: